### ISSUE TITLE
requirements on the hw design

### ISSUE THREAD

**Issue by e33b1711** [mstuehn/dma_proxy#1]
Hi,
i am trying to run the design on zynq / petalinux. The proxy_dma driver is loaded but when i run the build in test or the user space test i get a timeout. On https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/18842418/Linux+DMA+From+User+Space#LinuxDMAFromUserSpace-4DMAProxyDesign is a screen shot of a vivado block design with some details on the the axi_dma, there the scather / gather is on. In your code's comments says, it was tested without s/g. Could you give some infos (maybe some tcl) on the test setup hw design?

Thank you!

**Comment by mstuehn** [comment]
This repository is only for preserving purposes. I did not write the code, i only found it on the forum mentioned it in the description and preserved it as said in the description . Actually I've never used it at all.

**Comment by e33b1711** [comment]
Okay, thanks nontheless. If i find a working hw setup, shall i add some
comment or code?

Manuel Stühn <notifications@github.com> schrieb am Do., 27. Juni 2019,
20:17:

**Comment by mstuehn** [comment]
Yes, that would be ok. Sorry for not being much help.
